Submission: Automated log analysis action for GitHub Action pipelines
rominirani/genai-apptemplates-googlecloud pull request #6
Opened 2023-09-04 09:59 UTC by destrex271

2023-09-04 11:18 UTC, rominirani commented on palm-api-apps/palm_analysis_action/LICENSE
We will need to leave this LICENSE out and remove the file. We already have an APACHE license applied to the whole repo.

2023-09-04 11:20 UTC, rominirani requested changes
We will need to relook at the folder name. The location is current i.e. palm-api-apps but the name should ideally say something that its a github action, etc. So I suggest we have a name like `log-analysis-github-action`

2023-09-04 14:58 UTC, destrex271 commented
Removed the License and updated the folder name to log-analysis-github-action

2023-09-05 02:12 UTC, rominirani approved these changes

2023-09-05 02:12 UTC, merged